### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by AndyRPH** [jshank/jb-solaredge-docker#1]
I'm muddling with this, but not having luck. I've got a plain rpi3b setup.  What's the easiest way to load this docker image so I can give it a whirl?  I've got my switch setup to feed the pi's eth port a mirror of the traffic to/from the port the inverter will be connected to, then plan to connect to the pi itself via wifi. 

Or is using this docker more work than it's worth?

**Comment by jshank** [comment]
If this is going to be a dedicated RPi for this purpose, I wouldn't bother with the Docker image. It was really to use on a full blown x86 system that is running multiple purposes/images.

**Comment by AndyRPH** [comment]
It wasn't but considering it'll run 24/7 and listen to my traffic probably
not a bad idea.

On Feb 11, 2019, at 10:07 AM, Jim Shank <notifications@github.com> wrote:

If this is going to be a dedicated RPi for this purpose, I wouldn't bother
with the Docker image. It was really to use on a full blown x86 system that
is running multiple purposes/images.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jshank/jb-solaredge-docker/issues/1#issuecomment-462361124>,
or mute the thread
